apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  labels:
    last_updated: "1"
spec:
  rules:
  - host: cloud-build-demo.stephenmann.io
    http:
      paths:
      - path: /*
        backend:
          serviceName: hello-world
          servicePort: 80
